#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Evaluate admissible 6/7/9/10 treatment taxonomies for DCML.

This enhancement experiment addresses the reviewer question "why 6 and 10,
not 8?" without creating a new treatment family.  The script estimates all
theory-admissible granularity levels:

Composite-6         no decomposable family split
SplitFunctional-7   split only the MAI functional-visual family
SplitMarketing-9    split only the MNC marketing family
Component-10        split both decomposable families

Parent and child cues never enter the same causal regression.  A size-8
specification is therefore not generated by the prespecified taxonomy.
"""

from __future__ import annotations

# Portable publication paths; no experiment parameters are changed.
import sys as _dcml_sys
from pathlib import Path as _DCMLPath
_dcml_sys.path.insert(0, str(_DCMLPath(__file__).resolve().parents[1]))
import project_paths as _dcml_paths


import argparse
import json
import math
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

CURRENT_DIR = Path(__file__).resolve().parent
if str(CURRENT_DIR) not in sys.path:
    sys.path.insert(0, str(CURRENT_DIR))

from enhance_common import (  # noqa: E402
    CAUSAL_ROOT,
    DATASETS,
    OUTPUT_DIR,
    VERSION,
    add_holm_by_group,
    clean_component_name,
    ensure_output_dir,
    first_existing,
    read_table,
    write_json,
)


MIN_N = 500
MIN_SD = 0.02
MIN_IQR = 0.02
MIN_BINS = 4

PATHWAY = {
    "T_con_mkt": "MNC",
    "a_pri": "MNC",
    "a_gft": "MNC",
    "a_sub": "MNC",
    "a_urg": "MNC",
    "T_con_soc": "MNC",
    "T_con_rat": "MNC",
    "T_int_vis": "MAI",
    "a_spec": "MAI",
    "a_str": "MAI",
    "T_int_fac": "MAI",
    "T_align": "MAI",
}

DISPLAY = {
    "T_con_mkt": r"$T_{\mathrm{con,mkt}}$",
    "a_pri": r"$a_{\mathrm{pri}}$",
    "a_gft": r"$a_{\mathrm{gft}}$",
    "a_sub": r"$a_{\mathrm{sub}}$",
    "a_urg": r"$a_{\mathrm{urg}}$",
    "T_con_soc": r"$T_{\mathrm{con,soc}}$",
    "T_con_rat": r"$T_{\mathrm{con,rat}}$",
    "T_int_vis": r"$T_{\mathrm{int,vis}}$",
    "a_spec": r"$a_{\mathrm{spec}}$",
    "a_str": r"$a_{\mathrm{str}}$",
    "T_int_fac": r"$T_{\mathrm{int,fac}}$",
    "T_align": r"$T_{\mathrm{align}}$",
}

ALIASES = {
    "T_con_mkt": ["res_T_con_mkt_calib", "res_T_con_mkt_calibrated", "res_T_con_mkt"],
    "a_pri": [
        "res_atomic_a_pri_calib",
        "res_atomic_a_pri_calibrated",
        "res_atomic_a_pri",
        "res_atomic_mkt_price_calib",
        "res_atomic_mkt_price_calibrated",
        "res_atomic_mkt_price",
    ],
    "a_gft": ["res_atomic_a_gft_calib", "res_atomic_a_gft_calibrated", "res_atomic_a_gft"],
    "a_sub": ["res_atomic_a_sub_calib", "res_atomic_a_sub_calibrated", "res_atomic_a_sub"],
    "a_urg": ["res_atomic_a_urg_calib", "res_atomic_a_urg_calibrated", "res_atomic_a_urg"],
    "T_con_soc": ["res_T_con_soc"],
    "T_con_rat": ["res_T_con_rat"],
    "T_int_vis": ["res_T_int_vis_calib", "res_T_int_vis_calibrated", "res_T_int_vis"],
    "a_spec": ["res_atomic_a_spec_calib", "res_atomic_a_spec_calibrated", "res_atomic_a_spec"],
    "a_str": ["res_atomic_a_str_calib", "res_atomic_a_str_calibrated", "res_atomic_a_str"],
    "T_int_fac": ["res_T_int_fac_calib", "res_T_int_fac_calibrated", "res_T_int_fac"],
    "T_align": ["res_T_align", "res_T_int_sem"],
}

SPEC_DEFS = {
    "Composite-6": ["T_con_mkt", "T_con_soc", "T_con_rat", "T_int_vis", "T_int_fac", "T_align"],
    "SplitFunctional-7": [
        "T_con_mkt",
        "T_con_soc",
        "T_con_rat",
        "a_spec",
        "a_str",
        "T_int_fac",
        "T_align",
    ],
    "SplitMarketing-9": [
        "a_pri",
        "a_gft",
        "a_sub",
        "a_urg",
        "T_con_soc",
        "T_con_rat",
        "T_int_vis",
        "T_int_fac",
        "T_align",
    ],
    "Component-10": [
        "a_pri",
        "a_gft",
        "a_sub",
        "a_urg",
        "T_con_soc",
        "T_con_rat",
        "a_spec",
        "a_str",
        "T_int_fac",
        "T_align",
    ],
}


@dataclass(frozen=True)
class DatasetFiles:
    final_residual: Path
    gs_residual: Path | None
    schema: Path | None


class SimpleOLSResult:
    """Small fallback result object used when statsmodels is unavailable."""

    def __init__(self, names: list[str], beta: np.ndarray, covariance: np.ndarray) -> None:
        se = np.sqrt(np.maximum(np.diag(covariance), 0.0))
        t_values = np.divide(beta, se, out=np.full_like(beta, np.nan), where=se > 0)
        p_values = np.array([math.erfc(abs(t) / math.sqrt(2.0)) if np.isfinite(t) else np.nan for t in t_values])
        self.params = pd.Series(beta, index=names)
        self.bse = pd.Series(se, index=names)
        self.tvalues = pd.Series(t_values, index=names)
        self.pvalues = pd.Series(p_values, index=names)
        self._covariance = pd.DataFrame(covariance, index=names, columns=names)

    def cov_params(self) -> pd.DataFrame:
        return self._covariance


def dataset_files(dataset: str) -> DatasetFiles:
    base = _dcml_paths.workspace_path(CAUSAL_ROOT, 'processed_data') / dataset / "DML_Results"
    if dataset == "suning":
        final_candidates = [
            base / f"DCML_Residuals_{VERSION}.parquet",
            base / "DCML_Residuals_20260717.parquet",
            base / "DCML_Residuals_3.parquet",
            base / "*Residuals*.parquet",
            base / "*Residuals*.csv",
        ]
        gs_candidates = [
            base / f"DCML_GS_Training_Residuals_{VERSION}.parquet",
            base / "DCML_GS_Training_Residuals_20260717.parquet",
            base / "*GS*Residuals*.parquet",
            base / "*GS*Residuals*.csv",
        ]
        schema_candidates = [
            base / f"DML_feature_schema_{VERSION}.json",
            base / "DML_feature_schema_20260717.json",
            base / "*schema*.json",
        ]
    else:
        final_candidates = [
            base / f"{dataset}_DML_Residuals_Final_{VERSION}.parquet",
            base / f"{dataset}_DML_Residuals_Final_20260717.parquet",
            base / f"{dataset}_DML_Residuals_Final_2.parquet",
            base / f"{dataset}_DML_Residuals_Final.parquet",
            base / "*Residuals*.parquet",
            base / "*Residuals*.csv",
        ]
        gs_candidates = [
            base / f"{dataset}_DML_GS_Training_Residuals_{VERSION}.parquet",
            base / f"{dataset}_DML_GS_Training_Residuals_20260717.parquet",
            base / "*GS*Residuals*.parquet",
            base / "*GS*Residuals*.csv",
        ]
        schema_candidates = [
            base / f"{dataset}_DML_feature_schema_{VERSION}.json",
            base / f"{dataset}_DML_feature_schema_20260717.json",
            base / "*schema*.json",
        ]
    final = first_existing(final_candidates)
    if final is None:
        raise FileNotFoundError(f"{dataset}: no final residual file found in {base}")
    return DatasetFiles(
        final_residual=final,
        gs_residual=first_existing(gs_candidates),
        schema=first_existing(schema_candidates),
    )


def resolve_constructs(frame: pd.DataFrame, constructs: list[str]) -> tuple[dict[str, str], list[str]]:
    resolved: dict[str, str] = {}
    missing: list[str] = []
    for construct in constructs:
        hit = next((column for column in ALIASES[construct] if column in frame.columns), None)
        if hit is None:
            missing.append(construct)
        else:
            resolved[construct] = hit
    return resolved, missing


def infer_outcomes(frame: pd.DataFrame, dataset: str) -> list[str]:
    if dataset == "suning":
        preferred = ["res_y_click", "res_y_cart", "res_y_purchase"]
    else:
        preferred = ["res_y_purchase"]
    outcomes = [column for column in preferred if column in frame.columns]
    if outcomes:
        return outcomes
    fallback = [column for column in frame.columns if column.startswith("res_y_")]
    if not fallback:
        raise KeyError(f"{dataset}: no residual outcome column starting with res_y_ found")
    return sorted(fallback)


def support_diagnostics(values: pd.Series) -> dict:
    finite = pd.to_numeric(values, errors="coerce").replace([np.inf, -np.inf], np.nan).dropna()
    if finite.empty:
        return {
            "Estimable": False,
            "Support_Flag": "empty_treatment_residual",
            "Support_N": 0,
            "Residual_SD_Final": np.nan,
            "Residual_IQR_Final": np.nan,
            "Residual_Support_1_99_Final": np.nan,
            "Effective_Bins_10_Final": 0,
            "Min_Bin_Count_10_Final": 0,
            "Max_Bin_Share_10_Final": np.nan,
        }
    arr = finite.to_numpy(dtype=float)
    counts, _ = np.histogram(arr, bins=10)
    nonzero = counts[counts > 0]
    sd = float(np.std(arr, ddof=1)) if len(arr) > 1 else 0.0
    iqr = float(np.percentile(arr, 75) - np.percentile(arr, 25))
    width = float(np.percentile(arr, 99) - np.percentile(arr, 1))
    reasons = []
    if len(arr) < MIN_N:
        reasons.append("small_n")
    if sd < MIN_SD:
        reasons.append("low_residual_sd")
    if iqr < MIN_IQR:
        reasons.append("low_residual_iqr")
    if len(nonzero) < MIN_BINS:
        reasons.append("sparse_effective_bins")
    return {
        "Estimable": not reasons,
        "Support_Flag": "ok" if not reasons else "|".join(reasons),
        "Support_N": int(len(arr)),
        "Residual_SD_Final": sd,
        "Residual_IQR_Final": iqr,
        "Residual_Support_1_99_Final": width,
        "Effective_Bins_10_Final": int(len(nonzero)),
        "Min_Bin_Count_10_Final": int(nonzero.min()) if len(nonzero) else 0,
        "Max_Bin_Share_10_Final": float(counts.max() / len(arr)),
    }


def numeric_design(frame: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    return frame[columns].apply(pd.to_numeric, errors="coerce").replace([np.inf, -np.inf], np.nan)


def apply_projection(
    final: pd.DataFrame,
    gs_train: pd.DataFrame | None,
    construct_to_col: dict[str, str],
    spec: str,
    constructs: list[str],
    projection: str,
) -> tuple[pd.DataFrame, dict[str, str], str]:
    if projection == "none" or gs_train is None:
        return final.copy(), construct_to_col.copy(), "existing_final_residual_only"

    mnc = [c for c in constructs if PATHWAY[c] == "MNC"]
    mai = [c for c in constructs if PATHWAY[c] == "MAI"]
    controls = [construct_to_col[c] for c in mnc]
    targets = [construct_to_col[c] for c in mai]
    missing_train = [c for c in controls + targets if c not in gs_train.columns]
    if missing_train:
        return final.copy(), construct_to_col.copy(), "gs_training_file_missing_spec_columns"

    out = final.copy()
    mapping = construct_to_col.copy()
    train_x = numeric_design(gs_train, controls)
    final_x = numeric_design(final, controls)
    train_x.insert(0, "const", 1.0)
    final_x.insert(0, "const", 1.0)
    final_x = final_x.reindex(columns=train_x.columns, fill_value=0.0)
    for construct, target in zip(mai, targets):
        y_train = pd.to_numeric(gs_train[target], errors="coerce").replace([np.inf, -np.inf], np.nan)
        observed = y_train.notna() & train_x.notna().all(axis=1)
        pure = f"{target}__{spec.lower().replace('-', '_')}_gs_pure_{VERSION}"
        if int(observed.sum()) <= train_x.shape[1] + 5:
            out[pure] = np.nan
            mapping[construct] = pure
            continue
        x_obs = train_x.loc[observed].to_numpy(dtype=float)
        y_obs = y_train.loc[observed].to_numpy(dtype=float)
        coef = np.linalg.pinv(x_obs.T @ x_obs) @ x_obs.T @ y_obs
        raw = pd.to_numeric(final[target], errors="coerce").to_numpy(dtype=float)
        pred = np.asarray(final_x.to_numpy(dtype=float) @ coef, dtype=float)
        out[pure] = np.where(np.isfinite(raw), raw - pred, np.nan)
        mapping[construct] = pure
    return out, mapping, "train_fitted_mnc_to_mai_projection"


def fit_hc1_ols(complete: pd.DataFrame, outcome: str, columns: list[str]) -> SimpleOLSResult:
    names = ["const", *columns]
    x = np.column_stack([np.ones(len(complete)), complete[columns].to_numpy(dtype=float)])
    y = complete[outcome].to_numpy(dtype=float)
    xtx_inv = np.linalg.pinv(x.T @ x)
    beta = xtx_inv @ x.T @ y
    residual = y - x @ beta
    meat = x.T @ ((residual[:, None] ** 2) * x)
    n, k = x.shape
    scale = n / max(1, n - k)
    covariance = scale * xtx_inv @ meat @ xtx_inv
    return SimpleOLSResult(names, beta, covariance)


def fit_clustered_ols(frame: pd.DataFrame, outcome: str, columns: list[str]):
    complete = numeric_design(frame, [outcome] + columns).dropna()
    if len(complete) <= len(columns) + 5:
        raise RuntimeError("insufficient_complete_cases")
    try:
        import statsmodels.api as sm

        x = sm.add_constant(complete[columns], has_constant="add")
        base = sm.OLS(complete[outcome], x)
        if {"cluster_user_id", "cluster_item_id"}.issubset(frame.columns):
            clusters = frame.loc[complete.index, ["cluster_user_id", "cluster_item_id"]]
            user_codes = pd.factorize(clusters["cluster_user_id"].astype(str))[0]
            item_codes = pd.factorize(clusters["cluster_item_id"].astype(str))[0]
            try:
                model = base.fit(cov_type="cluster", cov_kwds={"groups": np.column_stack([user_codes, item_codes])})
                return model, complete.index, "two_way_cluster_user_item"
            except Exception:
                model = base.fit(cov_type="cluster", cov_kwds={"groups": user_codes})
                return model, complete.index, "cluster_user"
        model = base.fit(cov_type="HC1")
        return model, complete.index, "HC1_no_cluster_ids"
    except ImportError:
        return fit_hc1_ols(complete, outcome, columns), complete.index, "HC1_fallback_no_statsmodels"


def chi2_sf(statistic: float, df: int) -> float:
    try:
        import scipy.stats as stats

        return float(stats.chi2.sf(statistic, df))
    except ImportError:
        if df == 1:
            return math.erfc(math.sqrt(max(statistic, 0.0)) / math.sqrt(2.0))
        return np.nan


def wald_test(model, columns: list[str]) -> dict:
    names = list(model.params.index)
    included = [column for column in columns if column in names]
    if not included:
        return {"Statistic": np.nan, "DF": 0, "P_Value": np.nan}
    restriction = np.zeros((len(included), len(names)), dtype=float)
    for row_idx, column in enumerate(included):
        restriction[row_idx, names.index(column)] = 1.0
    try:
        test = model.wald_test(restriction, scalar=True)
        statistic = float(np.asarray(test.statistic).squeeze())
        p_value = float(np.asarray(test.pvalue).squeeze())
    except Exception:
        cov = np.asarray(model.cov_params(), dtype=float)
        beta = np.asarray(model.params, dtype=float)
        r_beta = restriction @ beta
        r_cov = restriction @ cov @ restriction.T
        statistic = float(r_beta.T @ np.linalg.pinv(r_cov) @ r_beta)
        p_value = chi2_sf(statistic, len(included))
    return {"Statistic": statistic, "DF": int(len(included)), "P_Value": p_value}


def rank_diagnostics(frame: pd.DataFrame, columns: list[str]) -> dict:
    complete = numeric_design(frame, columns).dropna()
    if complete.empty:
        return {"Rank": 0, "Cue_Count": len(columns), "Min_Eigenvalue": np.nan, "Condition_Number": np.nan}
    corr = complete.corr().replace([np.inf, -np.inf], np.nan).fillna(0.0).to_numpy(dtype=float)
    if corr.shape[0] == 1:
        return {"Rank": 1, "Cue_Count": 1, "Min_Eigenvalue": 1.0, "Condition_Number": 1.0}
    eig = np.linalg.eigvalsh(corr)
    positive = eig[eig > 1e-10]
    condition = float(positive.max() / positive.min()) if len(positive) else np.nan
    return {
        "Rank": int(np.linalg.matrix_rank(corr)),
        "Cue_Count": int(len(columns)),
        "Min_Eigenvalue": float(eig.min()),
        "Condition_Number": condition,
    }


def taxonomy_table() -> pd.DataFrame:
    rows = []
    for spec, constructs in SPEC_DEFS.items():
        split_marketing = all(c in constructs for c in ["a_pri", "a_gft", "a_sub", "a_urg"])
        split_functional = all(c in constructs for c in ["a_spec", "a_str"])
        rows.append(
            {
                "Specification": spec,
                "Treatment_Count": len(constructs),
                "Split_Marketing_Family": split_marketing,
                "Split_Functional_Visual_Family": split_functional,
                "Admissible": True,
                "Constructs": "|".join(constructs),
                "Rationale": (
                    "generated by the prespecified rule: each decomposable parent is either retained as a parent "
                    "or fully replaced by all of its components; parent and child never coexist"
                ),
            }
        )
    rows.append(
        {
            "Specification": "Any-8",
            "Treatment_Count": 8,
            "Split_Marketing_Family": np.nan,
            "Split_Functional_Visual_Family": np.nan,
            "Admissible": False,
            "Constructs": "",
            "Rationale": (
                "not generated by the taxonomy because full replacement of the 4-component marketing family "
                "changes count by +3 and full replacement of the 2-component functional family changes count by +1"
            ),
        }
    )
    return pd.DataFrame(rows)


def run_dataset(dataset: str, projection: str) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, dict]:
    files = dataset_files(dataset)
    final = read_table(files.final_residual)
    gs_train = read_table(files.gs_residual) if files.gs_residual is not None and projection == "auto" else None
    outcomes = infer_outcomes(final, dataset)

    ate_rows = []
    wald_rows = []
    diagnostic_rows = []
    file_manifest = {
        "final_residual": str(files.final_residual),
        "gs_residual": str(files.gs_residual) if files.gs_residual else None,
        "schema": str(files.schema) if files.schema else None,
        "outcomes": outcomes,
    }

    for spec, constructs in SPEC_DEFS.items():
        resolved, missing = resolve_constructs(final, constructs)
        diagnostic_base = {
            "Dataset": dataset,
            "Specification": spec,
            "Requested_Treatment_Count": len(constructs),
            "Missing_Constructs": "|".join(missing),
        }
        if missing:
            diagnostic_rows.append(
                {
                    **diagnostic_base,
                    "Estimated_Treatment_Count": 0,
                    "Rank": 0,
                    "Cue_Count": len(constructs),
                    "Min_Eigenvalue": np.nan,
                    "Condition_Number": np.nan,
                    "Projection_Status": "skipped_missing_constructs",
                }
            )
            continue
        analysis, mapping, projection_status = apply_projection(final, gs_train, resolved, spec, constructs, projection)
        support = {construct: support_diagnostics(analysis[mapping[construct]]) for construct in constructs}
        estimable_constructs = [construct for construct in constructs if support[construct]["Estimable"]]
        estimable_cols = [mapping[construct] for construct in estimable_constructs]
        rank = rank_diagnostics(analysis, estimable_cols)
        diagnostic_rows.append(
            {
                **diagnostic_base,
                "Estimated_Treatment_Count": len(estimable_constructs),
                "Estimated_Constructs": "|".join(estimable_constructs),
                "Projection_Status": projection_status,
                **rank,
            }
        )
        for construct in constructs:
            diagnostic_rows.append(
                {
                    **diagnostic_base,
                    "Diagnostic_Level": "treatment_support",
                    "Construct": construct,
                    "Display_Name": DISPLAY[construct],
                    "Pathway": PATHWAY[construct],
                    "Treatment_Column": mapping.get(construct, ""),
                    "Projection_Status": projection_status,
                    **support[construct],
                }
            )
        if not estimable_cols:
            continue
        for outcome in outcomes:
            stage = outcome.replace("res_y_", "")
            try:
                model, model_index, covariance = fit_clustered_ols(analysis, outcome, estimable_cols)
            except RuntimeError as exc:
                ate_rows.append(
                    {
                        "Dataset": dataset,
                        "Specification": spec,
                        "Stage": stage,
                        "Construct": "",
                        "Error": str(exc),
                        "Projection_Status": projection_status,
                    }
                )
                continue
            for construct in constructs:
                column = mapping[construct]
                row = {
                    "Dataset": dataset,
                    "Specification": spec,
                    "Stage": stage,
                    "Construct": construct,
                    "Display_Name": DISPLAY[construct],
                    "Pathway": PATHWAY[construct],
                    "Treatment_Column": column,
                    "N": int(len(model_index)),
                    "Covariance": covariance,
                    "Projection_Status": projection_status,
                    **support[construct],
                }
                if construct in estimable_constructs:
                    row.update(
                        {
                            "Coefficient": float(model.params[column]),
                            "Std_Error": float(model.bse[column]),
                            "T_Stat": float(model.tvalues[column]),
                            "P_Value": float(model.pvalues[column]),
                            "Sign": int(math.copysign(1, model.params[column])) if model.params[column] != 0 else 0,
                        }
                    )
                else:
                    row.update(
                        {
                            "Coefficient": np.nan,
                            "Std_Error": np.nan,
                            "T_Stat": np.nan,
                            "P_Value": np.nan,
                            "Sign": np.nan,
                        }
                    )
                ate_rows.append(row)
            for pathway in ["MNC", "MAI"]:
                pathway_constructs = [c for c in estimable_constructs if PATHWAY[c] == pathway]
                pathway_columns = [mapping[c] for c in pathway_constructs]
                wald_rows.append(
                    {
                        "Dataset": dataset,
                        "Specification": spec,
                        "Stage": stage,
                        "Pathway": pathway,
                        "Cue_Count": len(pathway_columns),
                        "Constructs": "|".join(pathway_constructs),
                        "N": int(len(model_index)),
                        "Covariance": covariance,
                        "Projection_Status": projection_status,
                        **wald_test(model, pathway_columns),
                    }
                )
    return pd.DataFrame(ate_rows), pd.DataFrame(wald_rows), pd.DataFrame(diagnostic_rows), file_manifest


def focal_stability(ate: pd.DataFrame) -> pd.DataFrame:
    if ate.empty or "Construct" not in ate.columns:
        return pd.DataFrame()
    focal = ate[ate["Construct"].isin(["T_con_soc", "T_align"])].copy()
    if focal.empty:
        return focal
    rows = []
    for keys, group in focal.groupby(["Dataset", "Stage", "Construct"], dropna=False):
        valid = group.dropna(subset=["Coefficient"])
        if valid.empty:
            continue
        signs = valid["Coefficient"].apply(np.sign)
        rows.append(
            {
                "Dataset": keys[0],
                "Stage": keys[1],
                "Construct": keys[2],
                "Specifications_Estimated": int(valid["Specification"].nunique()),
                "Sign_Stable_Across_Admissible_Specs": bool(signs.nunique() == 1),
                "Min_Coefficient": float(valid["Coefficient"].min()),
                "Max_Coefficient": float(valid["Coefficient"].max()),
                "Coefficient_Range": float(valid["Coefficient"].max() - valid["Coefficient"].min()),
                "Holm_Significant_Specifications": int(valid.get("Significant_Holm_05", pd.Series(False)).fillna(False).sum()),
                "Specifications": "|".join(valid["Specification"].astype(str)),
            }
        )
    return pd.DataFrame(rows)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", choices=[*DATASETS, "all"], default="all")
    parser.add_argument(
        "--projection",
        choices=["auto", "none"],
        default="auto",
        help="auto uses GS training residuals when available; none uses existing final residual columns.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    ensure_output_dir()
    selected = DATASETS if args.dataset == "all" else (args.dataset,)
    all_ate = []
    all_wald = []
    all_diag = []
    manifest = {
        "version": VERSION,
        "experiment": "theory-admissible taxonomy sensitivity",
        "projection_argument": args.projection,
        "support_thresholds": {
            "min_n": MIN_N,
            "min_sd": MIN_SD,
            "min_iqr": MIN_IQR,
            "min_bins": MIN_BINS,
        },
        "dataset_files": {},
        "specifications": SPEC_DEFS,
        "nonadmissible_size_8_rule": (
            "A size-8 model is not generated by the prespecified replacement rules. "
            "Splitting marketing changes the count by +3, splitting functional visuals changes it by +1."
        ),
    }
    taxonomy = taxonomy_table()
    taxonomy.to_csv(OUTPUT_DIR / f"Taxonomy_Admissible_Specifications_{VERSION}.csv", index=False)
    for dataset in selected:
        ate, wald, diag, file_manifest = run_dataset(dataset, args.projection)
        all_ate.append(ate)
        all_wald.append(wald)
        all_diag.append(diag)
        manifest["dataset_files"][dataset] = file_manifest
    ate_df = pd.concat(all_ate, ignore_index=True) if all_ate else pd.DataFrame()
    if not ate_df.empty and "P_Value" in ate_df.columns:
        ate_df = add_holm_by_group(ate_df, ["Dataset", "Specification", "Stage"])
    wald_df = pd.concat(all_wald, ignore_index=True) if all_wald else pd.DataFrame()
    if not wald_df.empty and "P_Value" in wald_df.columns:
        wald_df = add_holm_by_group(wald_df, ["Dataset", "Specification", "Stage"])
    diag_df = pd.concat(all_diag, ignore_index=True) if all_diag else pd.DataFrame()
    focal_df = focal_stability(ate_df)

    ate_df.to_csv(OUTPUT_DIR / f"Taxonomy_Sensitivity_ATE_{VERSION}.csv", index=False)
    wald_df.to_csv(OUTPUT_DIR / f"Taxonomy_Sensitivity_Pathway_Wald_{VERSION}.csv", index=False)
    diag_df.to_csv(OUTPUT_DIR / f"Taxonomy_Sensitivity_Design_Diagnostics_{VERSION}.csv", index=False)
    focal_df.to_csv(OUTPUT_DIR / f"Taxonomy_Sensitivity_Focal_Stability_{VERSION}.csv", index=False)
    write_json(manifest, OUTPUT_DIR / f"Taxonomy_Sensitivity_Manifest_{VERSION}.json")
    print(f"Taxonomy sensitivity outputs written to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
